# Generated by Django 3.1.5 on 2021-03-22 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20210318_1007'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='datecompelted',
            new_name='datecompleted',
        ),
    ]
